version: '3'

services:
  postgres:
    image: postgres
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: balerion
      POSTGRES_PASSWORD: balerion
      POSTGRES_DB: balerion
    ports:
      - '5432:5432'

  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: balerion
      MYSQL_USER: balerion
      MYSQL_PASSWORD: balerion
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: balerion
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - '3306:3306'

volumes:
  pgdata:
  mysqldata:
